triggers:
- description: null
  envs: []
  last_enabled_at: 2024-07-13 22:19:30.061272+00:00
  name: Real-time predictions
  pipeline_uuid: predict
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-07-13 22:18:00+00:00
  status: active
  token: 8c097d3f177344128bee40a66210ce3b
  variables:
    DATE_TIME: date_time
